use_frameworks!

platform :ios, '11.0'

target 'ModularizacaoLu_Example' do
  pod 'ModularizacaoLu', :path => '../'

  target 'ModularizacaoLu_Tests' do
    inherit! :search_paths

    pod 'ProgressHUD'
  end
end
